### ISSUE TITLE
PHP 8.1 notice

### ISSUE THREAD

**Issue by gwenya** [TypeRocket/core#104]
In PHP 8.1, some standard library interfaces like `\JsonSerializable` have gotten proper return type declarations, which causes a notice when implementing classes don't specify a return type:

```
Return type of TypeRocket\Models\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

Adding the `#[\ReturnTypeWillChange]` attribute would suppress the notice until PHP 9.0, while adding the proper return types will permanently get rid of it.

I haven't yet checked what other classes besides `TypeRocket\Models\Model` have this problem, I could do a PR for this as soon as I figure it out (if desired).

**Comment by kevindees** [comment]
Hey @gwenya 

I'll take a look at the `#[\ReturnTypeWillChange]` option and let you know. I think it will be the most viable to maintain PHP 7 compatibility.

Thanks,
Kevin

**Comment by kevindees** [comment]
Hey @gwenya

I have an update for this and it will go out with the next release. Thanks for pointing this one out.

Thanks,
Kevin
