### ISSUE TITLE
Deprecated Cookie error

### ISSUE THREAD

**Issue by Ced-Sharp** [TypeRocket/core#106]
In TypeRocket core, src/Http/Cookie.php, on line 101 and 143, NULL is being passed to the parameter "domain" of setcookie(), which is deprecated and throws an error (which shows the whoops error handler).

Setting it to an empty string seems to fix the issue.

**Comment by kevindees** [comment]
@Ced-Sharp, thanks for pointing this one out. This will be fixed in the next patch.
