### ISSUE TITLE
Deprecated mb_strlen error

### ISSUE THREAD

**Issue by Ced-Sharp** [TypeRocket/core#107]
In TypeRocket core, src/Http/Elements/Traits/MaxlengthTrait.php, on line 34, there is a chance that $value is NULL, which causes a deprecation error to be thrown (and show the whoops error handler).

Setting it to an empty string instead fixes the issue (I used the '?:' operator)

**Comment by kevindees** [comment]
@Ced-Sharp, this will be fixed in the next release.
