### ISSUE TITLE
Primary key name issue

### ISSUE THREAD

**Issue by themelaboratory** [TypeRocket/core#20]
Hi guys,

I think I found a bug related to the custom resource's primary key name. By default this column is named "**id**" and if you follow this convention everything works as expected. On the other hand if you try something more exotic ex. (**exotic_id**), the code will not work.

How to replicate this bug?
Create "base" Controller/Model with galaxy command line tool.  Set idColumn property in your Model to "exotic_id". Create a table with primary key named "exotic_id". Create **add** and **edit** views.

Make an entry to the database. Try to edit. (SQL Error - Column id does not exist!).

core/src/Models/Model.php:53

```
$this->query->table($table);       

// Should be:

$this->query->table($table);
$this->query->setIdColumn($this->idColumn);

```

core/src/Elements/Tables.php:333-343  should be replaced with:

```
if ($page->action == 'edit') {
       $edit_url = $page->getUrl(['route_id' => (int)$result->$columnId]);
}

if ($page->action == 'show') {
    $show_url = $page->getUrl(['route_id' => (int)$result->$columnId]);
}

if ($page->action == 'delete') {
    $delete_url = $page->getUrl(['route_id' => (int)$result->$columnId]);
}
```

Cheers,
M.

**Comment by kevindees** [comment]
Hey @themelaboratory 

Thanks for making me aware. I have summited a patch for this in version 4 beta7.

Thanks,
Kevin

**Comment by themelaboratory** [comment]
Hi @kevindees ,

In addition to my previous comment there is one more line to change.

**"belongsTo method"**
**core/src/Models/Model.php:1146** 

`return $relationship->where( $this->getIdColumn(), $id)->take(1);`
Should be
`return $relationship->where( $relationship->getIdColumn(), $id)->take(1);`

As I mentioned earlier, the bug can be reproduced if you replace default primary key name "id" to anything else.
I hope this make sense to you. 

Cheers,
Milos

**Comment by kevindees** [comment]
This is now fixed in beta19 https://github.com/TypeRocket/core/releases/tag/v4.0.0-beta19
