### ISSUE TITLE
Add filter when casting properties in model

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/core#29]
In the base model, the `provisionFields` method has a filter at the end: 
```php       
 return apply_filters( 'tr_model_provision_fields', $fields, $this );
```

It would useful to have the same kind of filter in the `castProperties` method.

**Comment by kevindees** [comment]
@nebulousGirl 

This feature has now been added to core. Great request.

https://github.com/TypeRocket/core/commit/35bd581173762ed17e8cde9398b6a5506590e7c6
