### ISSUE TITLE
WPUser class throws a notice when user is not found

### ISSUE THREAD

**Issue by nullvariable** [TypeRocket/core#44]
Not sure what the expected behavior would be, but if I use a user id that does not exist, I get a notice:

```
Notice: Trying to get property 'data' of non-object in ..../typerocket/vendor/typerocket/core/src/Models/WPUser.php on line 64
--
  |  
  | Call Stack:
  | 0.0001     428752   1. {main}() /app/index.php:0
  | 0.0001     429040   2. require('/app/wp-blog-header.php') /app/index.php:17
  | 0.2115   14645880   3. wp() /app/wp-blog-header.php:16
  | 0.2115   14645904   4. WP->main() /app/wp-includes/functions.php:964
  | 0.2148   14737696   5. WP->query_posts() /app/wp-includes/class-wp.php:717
  | 0.2148   14737856   6. WP_Query->query() /app/wp-includes/class-wp.php:601
  | 0.2148   14737856   7. WP_Query->get_posts() /app/wp-includes/class-wp-query.php:3230
  | 0.2155   14757696   8. apply_filters_ref_array() /app/wp-includes/class-wp-query.php:2706
  | 0.2155   14757696   9. WP_Hook->apply_filters() /app/wp-includes/plugin.php:244
  | 0.2155   14759200  10. ....\Core->posts_clauses_request() /app/wp-includes/class-wp-hook.php:286
  | 0.2156   14763264  11. App\Models\User->findById() /app/wp-content/mu-plugins/..../includes/core.php:169
```
I can check the user object for an ID at that point, and it will return a null value.

Essentially the `$user->data` property returned by the `get_user_by` function is null when the user doesn't exist, so trying to set the result using that property fails. For my use case, I need the user object, even if the user doesn't exist ( or is logged out ).

It's easy for me to check for logged out user ids since that will always be 0, but if for some reason there was a case where a user id that wasn't zero didn't exist, I feel like the WPUser object should be more informative. @kevindees Thoughts?

**Comment by kevindees** [comment]
Hey @nullvariable 

Good question. What is the code resulting in this error? Would you want it to throw a specific error or return an error bag object as the data prop?

**Comment by nullvariable** [comment]
v4.0.0-beta25
```
$user = new \App\Models\User();
$user = $user->findById( 0 );
```

I'm open to options, and happy to write a PR. Either way, I'd want to test that I actually got a user object back (without using find or die). Or if it threw an Exception I could wrap it in a try statement.

**Comment by nullvariable** [comment]
same results for `\TypeRocket\Models\WPUser`

**Comment by kevindees** [comment]
@nullvariable 

Does this do it? https://github.com/TypeRocket/core/commit/b518f4215b769db91b841ac23f66a11481f20953

**Comment by nullvariable** [comment]
@kevindees that's perfect :tada:
