### ISSUE TITLE
Invalid PHPDoc blocks

### ISSUE THREAD

**Issue by szepeviktor** [TypeRocket/core#51]
Hello!

core may have 311 lines of invalid PHPDoc values.
Would you welcome a PR?

**Comment by kevindees** [comment]
@szepeviktor 

If you wanted to do a PR for a sample group first I'm open to it. Then we can go from there.

**Comment by szepeviktor** [comment]
@kevindees While working (`grep -rFl '@param $'|xargs -L1 sed -e 's#@param $#@param string $#' -i`) on this I've noticed
- if/else
- if(if/else)/else(if)
- and so on, basically if/else/foreach are the building blocks of TypeRocket

Do you have plans to go more object oriented?

**Comment by kevindees** [comment]
@szepeviktor 

I do not have plans to go full-on OOP with the logic. I like a mix of functional and OOP personally but I'm always open to refactors as long as it doesn't negatively impact performance.

**Comment by szepeviktor** [comment]
```
$ find src/ -type f | wc -l
136 files

$ grep -r 'if \?(' src/ | wc -l
903 if-s
```

So 6.6 branchings per class. That we may call an **If Jungle**.

**Comment by kevindees** [comment]
@szepeviktor 

If there is a class you want to refactor and add a PR for I'm open to seeing your ideas to help clean things up.

**Comment by szepeviktor** [comment]
You can get rid of almost all `else`-s by early exiting:

```php
// Current code
if($found) {
    $this->success('Seeded config/app.php with: ' . $seed );
} else {
    $this->error('Manually Seed config/app.php with: ' . $seed);
}

// Errors go into `if`-s
if (!$found) {
    $this->error('Manually Seed config/app.php with: ' . $seed);
    return;
}

// Normal execution is not indented -> much cleaner 😸
$this->success('Seeded config/app.php with: ' . $seed );
```

**Comment by szepeviktor** [comment]
PHPDoc blocks are almost 💯% okay.

**Comment by kevindees** [comment]
@szepeviktor 

If you wanted to do a PR for these kinds of issues I'm all for it. Would love to have help getting the code cleaned up and optimized.

**Comment by szepeviktor** [comment]
You can start using `ObjectCalisthenics.ControlStructures.NoElse` from https://github.com/object-calisthenics/phpcs-calisthenics-rules today! See my [living docs](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.md#coding-style--coding-standard).
