### ISSUE TITLE
Date field type format

### ISSUE THREAD

**Issue by galingong** [TypeRocket/core#60]
Date type custom fields (eg. `$form->date('event_date')`) are formatted dd/mm/yyyy - input fields have their values in this format, and are also saved in the database like this. The default format for `<input type="date">` should be yyyy-mm-dd. I'm aware that these are not `type="date"` fields, but still should be formatted like so.
When parsing these dates from the database, php mixes up months with days. (eg. if you do something like `new DateTime($post->event_date)`, it returns a DateTime object with the month and day mixed up).

Edit: As a workaround, I could use `$form->text('event_date')->setAttribute('type', 'date')`, which works as it should, so not a big deal, but the feature should still work correctly once it's implemented.

**Comment by kevindees** [comment]
@galingong 

You can use the `setFormat()` method on the date field to set the format to your liking.

**Comment by galingong** [comment]
@kevindees Cool, thanks!

**Comment by fredy31** [comment]
So... how are you supposed to use setFormat?

**Comment by kevindees** [comment]
@fredy31 

You can use any of the jQuery date picker formats you want with it. https://jqueryui.com/datepicker/#date-formats

```php
$$form->date('My Date')->setFormat('mm/dd/yy');
```
