### ISSUE TITLE
Example frontend app?

### ISSUE THREAD

**Issue by Chematronix** [TypeRocket/core#61]
Hi,

this project looks great.  I can't imagine why it hasn't gonne viral yet.  Except, perhaps, because of the learning curve.  The docs could be improved (at least for those of us not familiar with Laravel), and specially, because I can't find any example frontend app to play with.  I'm trying to create a "Book" example picking up the tidbits from the docs, but I keep hitting wall after wall.  Might I suggest you publish one to make for a smoother TypeRocket launch?

Something like http://todomvc.com/ would be great (and good publicity too ;)

**Comment by kevindees** [comment]
Hey @Chematronix 

Thanks for this suggestion. We have been adding a few videos and they can be found here. I hope to get some front-end videos created soon.

https://www.youtube.com/typerocket

Thanks,
Kevin
