### ISSUE TITLE
Ability to format search results

### ISSUE THREAD

**Issue by marbetschar** [TypeRocket/core#65]
It would be awesome to be able to customize the way search results are displayed. Right now it seems the JavaScript implementation is rather static and does not allow for customizations:

https://github.com/TypeRocket/core/blob/a5311cc7d20dd6ff795b2008952de79b343d8896/assets/js/tooling/search.js#L25-L39

**Comment by kevindees** [comment]
Hey @marbetschar 

We are working on a new version of TypeRocket that has this feature. Stay tuned :)

Thanks,
Kevin
