### ISSUE TITLE
typerocket theme dependence

### ISSUE THREAD

**Issue by augustusmax** [TypeRocket/core#67]
Hello, I am impressed by the typerocket framework and want to use it embedded in my plugin but I am concerned that it is dependent on the installed theme. I would like my plugin to operate regardless of theme being deleted/changed.

Looking at the config, it appears the use of the theme directory is hardcoded for important TR directories like 'resources'. Is this correct or am I missing something?

I saw in Issue #21 discussing namespace which was another concern given one of my plugin users has typerocket already installed. What is the best practice for handling compatibility if I wanted to accomplish a standalone theme-independent plugin powered by TypeRocket?

thank you

**Comment by kevindees** [comment]
Hey @augustusmax 

You can install typerocket into an MU plugin as well.

https://typerocket.com/docs/v4/installation/#section-mu-plugin

Thanks,
Kevin
