### ISSUE TITLE
How add select field with options from custom taxonomies in admin theme options

### ISSUE THREAD

**Issue by jsonpreet** [TypeRocket/core#69]
How add select field with options from custom taxonomies in admin theme options?

I used $form->select('Gender')->setOptions(array('Male' => 'm'));
but it show empty select without any options. I m trying to show taxonomy in dropdown list.

**Comment by tomislav13** [comment]
Try this:
`echo $form->select('gender')->setOptions(array('Male' => 'm', 'Female' => 'f'));`
1st parameter of select() method is the name of the field.
