### ISSUE TITLE
Form fields - hide bug icon

### ISSUE THREAD

**Issue by tomislav13** [TypeRocket/core#74]
Regards,
how to hide bug icon (div with css class 'dev') on all typerocket form fields?
I need to hide it for certain wordpress user roles.
I could do it with jQuery, but is there some typerocket option to do just that?

**Comment by kevindees** [comment]
Hey @tomislav13 

You need to set WP_DEBUG to false.

**Comment by tomislav13** [comment]
Oh, that makes sense, thank you.
