### ISSUE TITLE
Invalid CSRF Token on post() route

### ISSUE THREAD

**Issue by tomislav13** [TypeRocket/core#75]
Regards,
I am using wordpress 5.3 and PHP 7.2. with typerocket as a plugin, to create some frontend routes. GET requests are working, but POST routes do not. Example: tr_route()->post()->match('data/post')->do('test@Data') return this error: "Invalid CSRF Token". So I investigated typerocket core a little and
found that TR needs some special POST field named like this: 
`$token = check_ajax_referer( 'form_' . Config::locate('app.seed'), '_tr_nonce_form', false );`
 And I tried to create nonce with: 
`wp_create_nonce('form_<APP_SEED>_tr_nonce_form');`
and put it's response into next post request like this 
`_ajax_nonce=c87565cbaf`
but this also returns the same error.
Also, when I comment out middleware file "BaseVerify.php" lines 26-31 then
the post requests begin to work, but this is only temporary solution.
Can you help, or point to some relevant docs,

Thanks

**Comment by tomislav13** [comment]
UPDATE:
I've found the solution:
1. create the nonce `wp_create_nonce('form_' . Config::locate('app.seed'));`
2. create new POST request with post params like this:
**_wpnonce=YOUR_NONCE&_method=POST**&yourField1=yourValue1

Also, my other problem was in firefox dev tools,
I've had to create new POST request by right clicking on request and picking "Open in new tab" option.

**Comment by hex0id** [comment]
shouldn't this be in the documentation @kevindees ?

**Comment by hex0id** [comment]
in case someone is making custom form, there's an easier way to achieve what @tomislav13 
 achieved, just use:

`<?= tr_field_nonce(); ?>`

Inside your form tags.

**Comment by kevindees** [comment]
Hey @hex0id @tomislav13 

This is now documented in v5.

Thanks,
Kevin
