### ISSUE TITLE
Raw sql for order by (model query)

### ISSUE THREAD

**Issue by tomislav13** [TypeRocket/core#76]
Regards,
I have a model where I need to pull 15 random rows,
but this didn't work: 
`->orderBy(NULL, 'RAND()') // params are only $column and $direction`
But I found the solution/hack with this:
`->appendRawWhere(null, 'ORDER BY RAND()')`
Is there some other way to add custom sql?

**Comment by kevindees** [comment]
Hey @tomislav13 

This feature has been added.

Thanks,
Kevin
