### ISSUE TITLE
Can't modify request fields in view, WPPostController::create() fails silently if there's no post_title

### ISSUE THREAD

**Issue by Chematronix** [TypeRocket/core#78]
Hi,

I'd like to set post_title on the fly in my view, like so:
```
    public function create()
    {
	‌‌$this->request->fields['post_title'] = $this->fields['first_name'] .' '. $this->fields['last_name'];
	parent::create();
    }
```
But request->fields is protected, so that won't work.  What's the best way to do it?

In Laravel you can do something like:
```
  $request->request->add(['new_field' => 'yup']);
  User::create($request->all());
```
Also, if I simply don't set post_title (nor any other $builtin field), WPPost::create() fails without throwing any error, because of all the checks being inside `if ( ! empty( $builtin ))`.  The same would happen for update(), if I tried very hard. :)

**Comment by kevindees** [comment]
Hey @Chematronix 

The `tr_model_provision_fields` filter might be what you need to use.

```php
public function create()
{
    add_filter('tr_model_provision_fields', function() {
        ‌‌$this->request->fields['post_title'] = $this->fields['first_name'] .' '. $this->fields['last_name'];
    });

    parent::create();
}
```

Thanks,
Kevin

**Comment by Chematronix** [comment]
That gives the same error: `Cannot access protected property TypeRocket\Http\Request::$fields`, but this worked:

```
			add_filter( 'tr_model_provision_fields', function ( $fields ) {
				$fields['post_title'] = $fields['name'];
				return $fields;
			});
```
Thanks to you!

(some clarification about $fields, $this->fields and $this->request->fields would come handy)
