### ISSUE TITLE
Can i somehow create Signature Fields

### ISSUE THREAD

**Issue by reinhardjung** [TypeRocket/core#79]
Hi

Can i somehow create Signature Fields (CPT-Field), so my Users can sign a Form?

thanx a lot for any hint

**Comment by kevindees** [comment]
Hey @reinhardjung 

You will need to create your own custom field to do that.  https://typerocket.com/docs/v4/custom-fields/

Maybe try using this js lib? https://github.com/szimek/signature_pad

Thanks,
Kevin

**Comment by reinhardjung** [comment]
Hey @kevindees 
It looks great and i'll dive into it!

Thanx a lot for his Hint
  Reinhard
