### ISSUE TITLE
Add metabox to post(page) ID

### ISSUE THREAD

**Issue by tr0yka** [TypeRocket/core#8]
Need add metabox only to ID element.

**Comment by kevindees** [comment]
Hey @tr0yka 

I'm not sure what you are asking about. If you can send more information about what you are trying to do that would be great. However, to use just the ID of the screen you need to use the `addScreen()` method.

The ID of a post type like `post`.

```php
$your_id = 'post';
$box = tr_meta_box('Details');
$box->addScreen( $your_id );
```

Or the dashboard,

```php
$box = tr_meta_box('Dash Details');
$box->addScreen('dashboard');
```

You can read all the information here was well: https://typerocket.com/docs/v3/meta-boxes/#section-dashboard-meta-box

**Comment by tr0yka** [comment]
@kevindees 
Not screen ID. Need Post ID. 
Ex. : $id = get_required_object_id(); 
or
Custom set post id to add metabox.
`
$box = tr_meta_box('Details');
$box->addScreen( $postID );
`

**Comment by kevindees** [comment]
Hey @tr0yka unfortunately the system is not designed with an API for that. You would need to add that kind of feature manually but it would not keep you from using custom fields in your own metabox. Just be sure to wrap the typerocket form in an HTML container with the class of `typerocket-container` like so:

```html
<div class="typerocket-container">
<?php // add your custom fields and form here ?>
</div>
```
