### ISSUE TITLE
Adding Repeater fields the other Way?

### ISSUE THREAD

**Issue by reinhardjung** [TypeRocket/core#80]
Hi @kevindees 

First off all. I really felt in Love with TypeRocket. Even that i'm totally new to WordPress Developing (i developed more than 10 Year with ColdFusion). I was able to get into it extremly fast, mostly because of TypeRocket - so thanx a lot for this cool Magic!

I still got some Issue with changeing from /mu-plugin install to build-it, so i can public my new Plugin in WordPress Library as well. But i'll RTFM first again and hope i'll get it.

My Problem/Question is about the Repeater Fields.

How can i change the Usability so my Customers love to use it as well.
Now it is: That the "Add New" Button is on Top and the new Fields are dropping underneath.
What i love to do is, that the "Add new" Button is/stay at the Buttom and the new fields are inserted every time on top (over the "Add new" Button.

Because my Users are use to "add" things like this. And when they are adding nuew Invoice Positions, they have to rearange those (each) positiones every time.

Do you know what i mean?

![HowItIs](https://user-images.githubusercontent.com/298616/71847946-8c17fd00-30ce-11ea-9094-fde0d68c8234.png)

![HowItShouldBe](https://user-images.githubusercontent.com/298616/71848041-c2557c80-30ce-11ea-8976-d67e2d00354d.png)

**Comment by kevindees** [comment]
Hey @reinhardjung 

Thanks for the kind words about TypeRocket. It is very much appreciated.

TypeRocket does not offer this as a feature right now but you would be able to pull off what you are asking if you apply some flexbox CSS to your admin.

https://css-tricks.com/almanac/properties/f/flex-direction/

Not sure if this helps or not.

Thanks,
Kevin

**Comment by reinhardjung** [comment]
Hi @kevindees 

Well. i think it helps me. If i'm correct. I need to "playing" with some flex-direction and this will do the trick! Thanx!!!!
