### ISSUE TITLE
Pro version

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/core#82]
Hello
I heard there is a Pro version in the making.
Is there a release date already ?
Thx

**Comment by kevindees** [comment]
Hey @clemorphy 

Thanks for asking. It has been crazy the last week. Pro is now in soft launch mode. you get a copy here :) https://typerocket.com/pro/

**Comment by clemorphy** [comment]
@kevindees 
Is renewing the license every year required to use the product, or only required to access the updates and support ?

**Comment by kevindees** [comment]
@clemorphy 

Only for updates and support.

**Comment by clemorphy** [comment]
Thanx 👍 . I'll try to convince my manager that we HAVE to get this PRO version 😎
