### ISSUE TITLE
Best way to set a repeater field required

### ISSUE THREAD

**Issue by lukwi** [TypeRocket/core#83]
Hey,

first of all i want to say, that i really like TypeRocket! It gives me the possibility to extend post types, which comes from another plugin in a simple way. Great :)

I have just a little question. What is the best way to set a textfield required, which is defined in a repeater?
I think about to use the raw render setting and use html required attribute, but maybe there is better way to that.

Greetings from germany,

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

The way you are doing it is correct. I like to have all the validation handled by the backend. We plan to add a  lot more control over validation on the front-end to Pro in the future though.

Thanks,
Kevin
