### ISSUE TITLE
Validator - rules pass if variable not present in request

### ISSUE THREAD

**Issue by galingong** [TypeRocket/core#84]
I've had a weird problem with bots - a contact form sending empty emails. I've set some fields as "required", but if I posted the form without the `$_POST[tr]` array entirely (only `_tr_nonce_form` present), the validator passes - in these cases `$this->request->getFields()` returns an empty array.

What I did is checking manually eg. `isset($_POST['tr']['email'])` before the TypeRocket validator, but I suspect this shouldn't work like this.

**Comment by kevindees** [comment]
Hey @galingong 

I'll look into this and create a unit test to check the problem.

Thanks,
Kevin

**Comment by kevindees** [comment]
Hey @galingong 

I'm not able to produce your bug. Can you post your validator code?

```php
// my code test
$validator = tr_validator([
   'email' => 'required'
], []);

$errors = $validator->getErrors();
```

**Comment by galingong** [comment]
Basically it's the same with a few more fields. I tried your test - what is the value that you get for `$errors`? For me it's an empty array.

**Comment by kevindees** [comment]
I get this:

<img width="417" alt="Screen Shot 2020-02-05 at 4 31 39 PM" src="https://user-images.githubusercontent.com/348368/73885017-030ef580-4835-11ea-87ea-fb1c50bbd9f5.png">

**Comment by galingong** [comment]
Weird. It's a 1 y.o. site, I'm doing a clean WP+TR install tomorrow and test if I could reproduce. Thanks for your feedback.

**Comment by kevindees** [comment]
@galingong 

There have been a ton of updates to TypeRocket v4 over the last year. That might be the issue.

Thanks,
Kevin

**Comment by galingong** [comment]
Yeah, that was it. After updating the validator works as expected. Thanks, cheers!
