### ISSUE TITLE
WhereMeta behaves incorrectly when meta value doesn't exist

### ISSUE THREAD

**Issue by hayleybech** [TypeRocket/core#85]
The docs demonstrate the ability to check if a meta value equal to null. However, this only works if the meta_key exists in the table (was set earlier and then emptied). Therefore, there's no way to use whereMeta to check for the **existence** of a meta key and then check if it's blank.

From the docs:
`(new Post)
->whereMeta([
        [
            'column' => 'feature',
            'operator' => '!=',
            'value' => null
        ],...`

**Comment by kevindees** [comment]
Hey @haydenbech 

Can you post the query you are running and the result you are expecting?

Thanks,
Kevin

**Comment by kevindees** [comment]
This should be fixed now.
