### ISSUE TITLE
Unable to save data for custom posttype to custom table

### ISSUE THREAD

**Issue by lukwi** [TypeRocket/core#86]
Hey,

I don't know if it's my issue, but I can't save custom post type data into a custom table like in your tutorial on youtube, where the way is explained very good :)

It seems to be, there is a problem with the id-column, because columns will be created, with the correct data, but with NULL id.

What do I have to change to deal with `post_id` column correctly on the custom table?

That's my code:

```php
<?php
namespace App\Models;

use \TypeRocket\Models\WPPost;

class Fach extends WPPost
{
    protected $postType = 'fach';

    protected $metaless = [
    	'details',
    ];

    public function details(){
       return $this->hasOne(FachDetails::class, 'post_id');
    }
}
```

```php
<?php
namespace App\Controllers;

use \App\Models\Fach;
use \App\Models\FachDetails;
use \TypeRocket\Controllers\WPPostController;

class FachController extends WPPostController
{
    protected $modelClass = Fach::class;

    public function update($id = null){

    	$fields = $this->request->getFields('details');

    	console_log($id);

    	(new FachDetails())->findOrNew($id)->save($fields);

    	parent::update($id);

    }
}
```

```php
<?php
namespace App\Models;

use \TypeRocket\Models\Model;

class FachDetails extends Model
{

    protected $resource = 'fach_details';
    
    protected $fillable = [
        'methodik_db_id',
        'hochschultyp',
    	'untertitel'
    ];

    public function fach(){
       return $this->belongsTo(Fach::class, 'post_id');
    }
}
```

```php
<?php
namespace App\Models;

$fach = tr_post_type('Fach', 'Fächer');
$fach->setTitlePlaceholder( 'Fachname hier eingeben' );
$fach->setIcon('graduation');
$fach->setArgument('supports', ['title'] );
$fach->setSlug('faecher');
$fach->setEditorForm(function() {
    $form = tr_form()->setGroup('details');
    echo $form->text('Methodik-DB-ID')->setType('number');
    $options = [
        'Universitäten' => '1',
        'Fachhochschulen / HAW' => '2',
        'Berufsakademien' => '3',
    ];
    echo $form->select('Hochschultyp')->setOptions($options);
    echo $form->text('Untertitel');
});
```

**Comment by kevindees** [comment]
Hey @lukwi 

There was a typo in the video.

```php
// replace this
// (new FachDetails)->findOrNew($id)->save($fields);
(new FachDetails)->findFirstWhereOrNew('post_id', $id)->save($fields);
```

**Comment by lukwi** [comment]
Still doesn't work :(

This is what i get:

![Bildschirmfoto 2020-02-12 um 16 19 47](https://user-images.githubusercontent.com/19588272/74349119-0fa2c900-4db4-11ea-9eb8-0dc9fb74070d.png)

**Comment by lukwi** [comment]
If i set the id in the db table, it works fine.

**Comment by kevindees** [comment]
@lukwi 

You will need to add the `post_id` to the list of fields. Also, make sure the `post_id` field is set to fillable in the model.

```php
$fields['post_id'] = $id;
(new FachDetails)->findFirstWhereOrNew('post_id', $id)->save($fields);
```

**Comment by lukwi** [comment]
Thank you very much for the fast help! Now it works.

Great Framework, hope it will become more popular :)

**Comment by kevindees** [comment]
@lukwi 

Thanks :)

**Comment by lukwi** [comment]
One question again. tr_posts_field() function doesn't work in page template, when saving the post data into an extra table. Am i do something wrong or isn't it implemented? I use it like it's showing in the backend and it returns null. 
<img width="763" alt="Bildschirmfoto 2020-02-13 um 13 46 35" src="https://user-images.githubusercontent.com/19588272/74436784-530a3f80-4e67-11ea-926b-ced5d67bad16.png">

**Comment by kevindees** [comment]
Hey @lukwi 

Maybe try using `tr_posts_field('fach.methodik_db_id')`?

Thanks,
Kevin

**Comment by lukwi** [comment]
Still doesn't work, But it doesn't matter. Now i use a simple access function to get the details data.

Thanks again,

Lucas
