### ISSUE TITLE
Sortable columns not working + fix

### ISSUE THREAD

**Issue by synio-wesley** [TypeRocket/core#9]
Hi,

Using TypeRocket right now for a project because I kind of like both WordPress and Laravel.

Came across an issue regarding custom sorting of columns in admin.

In core/src/Register/Registry.php line 306 it says:
`add_filter( "manage_edit-{$pt}_sortable_columns", function() use ($new_column) {`
This should be:
`add_filter( "manage_edit-{$pt}_sortable_columns", function($columns) use ($new_column) {`

Otherwise only one the last of the new defined sortable columns will be sortable.

Kind regards
Wesley / Synio

**Comment by kevindees** [comment]
Hey Wesley,

Thanks for spotting this issue and creating the fix. I have created the patch for this bug. you can run composer update to get the changes.

https://github.com/TypeRocket/core/releases/tag/v3.0.40

Thanks,
Kevin
