### ISSUE TITLE
Upgrade from v3

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/core#95]
Hi

In order to upgrade from V3 to ProV1, is it easier to do :

> V3 --upgrade to--> V4 --upgrade to--> ProV1

or

> V3 --upgrade to--> ProV1

Thx

**Comment by kevindees** [comment]
Hey @clemorphy 

Upgrading will be a lot of work coming from v3. I would recommend upgrading right into Pro v1. We do not have docs a lot of docs for upgrading from v3 to v4 or from v4 to v5.

Also, Pro v5 (aka Pro v2) is right around the corner. But, the upgrade from Pro v1 to Pro v5 will not be nearly as hard and we plan to have solid docs around the upgrades. Also, any major upgrades we make moving forward will have much better documentation.

Thanks,
Kevin

**Comment by clemorphy** [comment]
Thanks @kevindees for the advice.
