### ISSUE TITLE
Unable to update Users with TypeRocket v4 and WordPress 5.5.3

### ISSUE THREAD

**Issue by lukwi** [TypeRocket/core#96]
Hey Kevin,

after updating to WP 5.5.3 we are unable to update user settings by calling /wp-admin/user-edit.php.
Following message is showing up:

**Invalid Controller Action: update@User:\App\Controllers\UserController** 

We don't use the UserController. Maybe it can be deleted to fix the problem or do you have any other solution?

I restored the site to a point with WordPress 5.5.1 but the problem still consists.

Greetings from Germany

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

What version of TR are you using?

Thanks,
Kevin

**Comment by lukwi** [comment]
It is version 4.0.18

**Comment by kevindees** [comment]
@lukwi 

Are you using the plugin or composer? If you are using composer can you post your `composer.json` file here?

Thanks,
Kevin

**Comment by lukwi** [comment]
We use the plugin.

**Comment by kevindees** [comment]
Hey @lukwi 

Do you have a custom `app` folder with a user model and controller in it?

`\App\Controllers\UserController`

https://github.com/TypeRocket/typerocket/blob/v4/app/Controllers/UserController.php

Thanks,
Kevin

**Comment by lukwi** [comment]
Hey Kevin,

no we don't use a custom user model and controller.
I also tried to delete the user model and controller from the plugin app folder, but still the same error if i try to update a user.

Greetings

Lucas

**Comment by lukwi** [comment]
Hey Kevin,

hope you had a good start into 2021.

After trying a little bit, i found out that the http folder caused the problem:

<img width="308" alt="Bildschirmfoto 2021-01-04 um 10 40 42" src="https://user-images.githubusercontent.com/19588272/103523803-b97fbe00-4e7c-11eb-97c7-d70a288fd797.png">

I deleded it and now users can be updated again :)

Greetings and thanks again for the support

Lucas
