### ISSUE TITLE
Notice: Trying to access array offset on value of type null - when creating a new WooCommerce product

### ISSUE THREAD

**Issue by galingong** [TypeRocket/core#97]
When creating a new WooCommerce product, above the form, there's a notice - the script tries to access an index on the return value of `Registry::getPostTypeResource($post_type)`, which is `null`.
![image](https://user-images.githubusercontent.com/24705916/100499261-5d809600-3168-11eb-8963-58e489e176ba.png)
typerocket/core - 4.2.2, WP - 5.5.3, WooCommerce - 4.7.1

**Comment by kevindees** [comment]
Hey @galingong 

Have you tried registering the post type using:

https://typerocket.com/docs/v4/json-api/#section-register-resources-post-types

```php
// example
Registry::addPostTypeResource('book', [
        'book', // singular
        'books', // plural
        '\App\Models\Book', // Model class
        '\App\Controllers\BookController', // Controller class
]);
```

Thanks,
Kevin

**Comment by galingong** [comment]
That was it, thank you. I didn't know I had to do that.
