### ISSUE TITLE
Duplicate _tr_nonce_form id's

### ISSUE THREAD

**Issue by DrYurets** [TypeRocket/core#99]
Hello.
WP 5.7, TypeRocket 5
If there are two forms on the same page, the form field id="_tr_nonce_form" are duplicated and a warning appears in the browser console:

`[DOM] Found 2 elements with non-unique id #_tr_nonce_form: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" id=​"_tr_nonce_form" name=​"_tr_nonce_form" value=​"e571642ca6">​`

How can you specify a separate ID for each of the generated nonce_fields?

**Comment by kevindees** [comment]
Hey @DrYurets 

This is not a big deal. The input fields using the ID all have the same value so this should not cause any bugs.

Thanks,
Kevin
